repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.82.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - --args=--config=.terraform-docs.yml
      - id: terraform_tflint
        name: TFLint (top-level)
        exclude: "(examples|modules|test)/"
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl --var='master_account_id=123'
      - id: terraform_tflint
        name: TFLint (modules)
        files: "modules/"
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl'
